### ISSUE TITLE
"Can't find I2C bus" on Ubuntu 16.04

### ISSUE THREAD

**Issue by devtronslab** [Unrud/init-headphone#9]
INFO:root:Version: 0.11
WARNING:root:Kernel parameter is missing: acpi_enforce_resources=lax
INFO:root:Trying to add module to the kernel: i2c_dev
INFO:root:Trying to add module to the kernel: i2c_i801
DEBUG:root:Available i2c busses: ['i915 gmbus ssc', 'i915 gmbus vga', 'i915 gmbus panel', 'i915 gmbus dpc', 'i915 gmbus dpb', 'i915 gmbus dpd', 'DPDDC-A', 'DPDDC-B']
DEBUG:root:Supported i2c bus names: ['SMBus I801 adapter']
ERROR:root:Can't find i2c bus
ERROR:root:Operation failed
DEBUG:root:Exception occurred:
Traceback (most recent call last):
  File "src/init-headphone", line 322, in <module>
    main()
  File "src/init-headphone", line 308, in main
    init()
  File "src/init-headphone", line 240, in init
    set_effect(DEFAULT_EFFECT)
  File "src/init-headphone", line 256, in set_effect
    DATA_ENABLE_OUTPUT)
  File "src/init-headphone", line 232, in write_data_to_device
    with do_checks_and_get_i2c_bus() as i2c_bus:
  File "src/init-headphone", line 219, in do_checks_and_get_i2c_bus
    raise RuntimeError("Can't find i2c bus")
RuntimeError: Can't find i2c bus

Any suggestions?

**Comment by Unrud** [comment]
There is the problem:

> WARNING:root:Kernel parameter is missing: acpi_enforce_resources=lax

If you have installed the Debian package, you have to reboot your computer.
If you have installed the script yourself, you need to add the kernel parameter to GRUB and then reboot your computer.

**Comment by devtronslab** [comment]
Yup, fixed it thanks!

**Comment by yejingchen** [comment]
Hello,

I read an article about the kernel parameter in [lm-sensors's FAQ](http://web.archive.org/web/20140630034601/http://www.lm-sensors.org/wiki/FAQ/Chapter3#Mysensorshavestoppedworkinginkernel2.6.31). It said the original method to operate on IO ports is somewhat dangerous and might **damage hardware** because the BIOS might be using the same port, and because of that the kernel requires the parameter `acpi_enforce_resources=lax` to gain old behavior since 2.6.31.

Is there a method to enable headphone in a safer way?

**Comment by Unrud** [comment]
> It said the original method to operate on IO ports is somewhat dangerous and might damage hardware because the BIOS might be using the same port

The Windows driver does the same.

> Is there a method to enable headphone in a safer way?

No
